include:
  - project: "devops/gitlab/ci-templates/ruby"
    ref: "sans-dind"
    file:
      - ".rspec.yml"
      - ".rubocop.yml"
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

stages:
  - test
  - deploy

rspec_app_test:
  stage: test
  image: ruby:3.2.2
  before_script:
    - bundle install -j $(nproc)
  extends:
    - .rspec
  tags:
    - build

rubocop_app_test:
  stage: test
  image: ruby:3.2.2
  before_script:
    - bundle install -j $(nproc)
  extends:
    - .rubocop
  tags:
    - build

# This step was inspired from Gitlab's example of gem publication:
# https://gitlab.com/gitlab-org/quality/pipeline-common/-/blob/master/ci/gem-release.yml
gem_publication:
  stage: deploy
  image: ruby:3.2.2
  variables:
    GEMSPEC_FILE: "${CI_PROJECT_NAME}.gemspec"
    VAULT_VERSION: "1.10.1"
  before_script:
    - | 
      apt-get update && apt-get -y install \
      wget \
      unzip && \
      wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip -O /tmp/vault_${VAULT_VERSION}.zip && \
      unzip /tmp/vault_${VAULT_VERSION}.zip -d /usr/bin && \
      rm -fr /tmp/vault_${VAULT_VERSION}.zip && \
      apt-get remove -y wget unzip && \
      apt-get clean
    - export VAULT_ADDR=${VAULT_URL}
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/${CI_SERVER_HOST}/login role=${JWT_ROLE} jwt=${CI_JOB_JWT})"
    - export GEM_HOST_API_KEY="$(vault kv get -field=rubygems_api_key ${VAULT_KV_ENDPOINT}${ENVIRONMENT})"
    - |
      gem -v
      rm -f ./*.gem
      [ -f "${GEMSPEC_FILE}" ] || (echo "No ${GEMSPEC_FILE} file found!" && exit 1)
    - '[ -n "${GEM_HOST_API_KEY}" ] || (echo "GEM_HOST_API_KEY is not set!" && exit 1)'
  script:
    - GEM_FILE=$(echo "${CI_PROJECT_NAME}-${CI_COMMIT_TAG:1}.gem")
    - |
      gem build "${GEMSPEC_FILE}"
      [ -f "${GEM_FILE}" ] || (echo "No ${GEM_FILE} file found!" && exit 1)
    - '[ "${DISABLE_GEM_PUSH}" == "true" ] || gem push "${GEM_FILE}"'
  rules:
    # - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\.[a-zA-Z0-9]+)?$/
  artifacts:
    paths:
      - "*.gem"
  tags:
    - deploy
